runtime: python312
app_engine_apis: true

instance_class: F2
automatic_scaling:
  target_cpu_utilization: .9
  max_instances: 4
  max_concurrent_requests: 80
  target_throughput_utilization: .9
  min_idle_instances: 0
  max_idle_instances: 0

entrypoint: gunicorn --timeout 120 -b :$PORT -w 2 main:app

env_variables:
  MEMCACHED_HOST: "APPENGINE"

handlers:
- url: /sprites
  static_dir: sprites

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /map
  static_dir: map

- url: /static
  static_dir: map/dist

- url: /netcode/.*
  script: auto
  secure: never

- url: /.*
  script: auto
  secure: always
